version: 0.2

env:
  variables:
    key: "AWS_ACCESS_KEY_ID"
    key: "AWS_SECRET_ACCESS_KEY"

phases:
  build:
    commands:
      - ls -al scripts/
      - ./scripts/deploy.sh
cache:
  paths:
    - "vendor/**/*"
